# Copyright 2020-2022 The Mumble Developers. All rights reserved.
# Use of this source code is governed by a BSD-style license
# that can be found in the LICENSE file at the root of the
# Mumble source tree or at <https://www.mumble.info/LICENSE>.

variables:
  MUMBLE_ENVIRONMENT_STORE: '$(Agent.ToolsDirectory)/MumbleBuild'
  MUMBLE_ENVIRONMENT_SOURCE: 'https://dl.mumble.info/build/vcpkg'
  MUMBLE_ENVIRONMENT_PATH: '$(MUMBLE_ENVIRONMENT_STORE)/$(MUMBLE_ENVIRONMENT_VERSION)'
  MUMBLE_ENVIRONMENT_TOOLCHAIN: '$(MUMBLE_ENVIRONMENT_PATH)/scripts/buildsystems/vcpkg.cmake'
  MUMBLE_SOURCE_COMMIT: '$(Build.SourceVersion)'
  MUMBLE_SOURCE_REPOSITORY: '$(Build.SourcesDirectory)'
  MUMBLE_BUILD_DIRECTORY: '$(Build.BinariesDirectory)'
  # We set this to an empty String explicitly as the variable is not set for PR builds but it is required
  # to be an empty String in that case. That's why we have to set it here. For Nightly builds the
  # variable is set on Azure itself.
  BUILD_NUMBER_TOKEN: ''

jobs:
  - job: Windows_x64
    workspace:
      clean: all
    timeoutInMinutes: 90
    pool:
      vmImage: 'windows-2022'
    variables:
      MUMBLE_ENVIRONMENT_VERSION: 'windows-static-1.5.x~2021-07-27~64f88807.x64'
      MUMBLE_ENVIRONMENT_TRIPLET: 'x64-windows-static-md'
      VCVARS_PATH: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat'
    steps:
    - template: steps_windows.yml
      parameters:
        arch: 'x64'

  - job: Windows_x86
    workspace:
      clean: all
    timeoutInMinutes: 120
    pool:
      vmImage: 'windows-2022'
    variables:
      MUMBLE_ENVIRONMENT_VERSION: 'windows-static-1.5.x~2021-07-27~64f88807.x86'
      MUMBLE_ENVIRONMENT_TRIPLET: 'x86-windows-static-md'
      VCVARS_PATH: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsamd64_x86.bat'
    steps:
    - template: steps_windows.yml
      parameters:
        arch: 'x86'

  - job: Linux
    workspace:
      clean: all
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - template: steps_linux.yml

  - job: macOS
    workspace:
      clean: all
    pool:
      vmImage: 'macOS-latest'
    variables:
      MUMBLE_ENVIRONMENT_VERSION: 'macos-static-1.5.x~2021-07-27~64f88807.x64'
    steps:
    - template: steps_macos.yml
      parameters:
        installEnvironment: true

  - job: Translations
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: .ci/azure-pipelines/install-environment_linux_translations.bash
      displayName: 'Install Qt tools'
    - script: .ci/azure-pipelines/assertNoTranslationChanges.sh
      displayName: 'Checking for translation changes'

  - job: Docs
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
      submodules: false
      fetchDepth: 1
    - script: .ci/azure-pipelines/checkDocs.bash
      displayName: 'Check documentation'
