name: Build

on: [push, pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  CMAKE_OPTIONS: |
      -Dtests=ON -Dsymbols=ON -Ddisplay-install-paths=ON
  MUMBLE_ENVIRONMENT_SOURCE: 'https://dl.mumble.info/build/vcpkg/'


jobs:
  build:
    strategy:
        fail-fast: false
        matrix:
            os: [ubuntu-18.04, ubuntu-20.04]
            type: [shared] # Currently the "static" build doesn't work for Linux systems
            arch: [64bit]
            
    runs-on: ${{ matrix.os }}

    steps:
    - name: Print diskspace
      run: df -BM
      shell: bash


    - uses: actions/checkout@v3
      with:
          submodules: 'recursive'
          fetch-depth: 1


    - name: Set environment variables
      run: $GITHUB_WORKSPACE/.github/workflows/set_environment_variables.sh "${{ matrix.os }}" "${{ matrix.type }}" "${{ matrix.arch }}" "${{ runner.workspace }}"
      shell: bash


    - uses: actions/cache@v2
      with:
          path: '${{ env.MUMBLE_BUILD_ENV_PATH }}'
          key: ${{ env.MUMBLE_ENVIRONMENT_VERSION }}


    - uses: ./.github/actions/install-dependencies
      with:
          type: ${{ matrix.type }}
          os: ${{ matrix.os }}
          arch: ${{ matrix.arch }}


    - name: Build
      run: ./.github/workflows/build.sh
      shell: bash
      env:
          MUMBLE_BUILD_NUMBER_TOKEN: ${{ secrets.BUILD_NUMBER_TOKEN }}

    - name: Test
      working-directory: ${{ github.workspace }}/build
      shell: bash
      run: QT_QPA_PLATFORM=offscreen ctest --output-on-failure -C $BUILD_TYPE

